#!/usr/bin/env python3
"""Validate one explicit product profile and materialize both runtime bindings."""

from __future__ import annotations

import argparse
import hashlib
import importlib
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PROFILE = "sample-neutral"
PROFILE_PATTERN = re.compile(r"^[a-z][a-z0-9-]{2,63}$")
APP_OUTPUT = Path("platform/app/server/generated/product-manifest.ts")
CLIENT_OUTPUT = Path("platform/app/client/src/generated/product-manifest.ts")
AGENT_OUTPUT = Path("platform/agent/generated/product_manifest.py")
EXTENSION_SLOT_FILE = "extension-slots.json"


def _contracts(root: Path):
    source = root / "packages" / "contracts" / "src"
    sys.path.insert(0, str(source))
    try:
        return importlib.import_module("insight_agent_harness_contracts")
    finally:
        sys.path.remove(str(source))


def manifest_path(root: Path, profile: str) -> Path:
    """Resolve a named profile without consulting deployment or environment names."""

    if not PROFILE_PATTERN.fullmatch(profile):
        raise ValueError(f"invalid profile {profile!r}; use an explicit lowercase profile name")
    return root / "profiles" / profile / "product.manifest.json"


def load_and_validate(root: Path, profile: str) -> tuple[dict[str, Any], bytes]:
    source_path = manifest_path(root, profile)
    try:
        source = source_path.read_bytes()
    except FileNotFoundError as error:
        raise ValueError(
            f"product manifest is missing for explicit profile {profile!r}: "
            f"{source_path.relative_to(root)}"
        ) from error
    try:
        value = json.loads(source)
    except json.JSONDecodeError as error:
        raise ValueError(
            f"{source_path.relative_to(root)} is not valid JSON: {error.msg}"
        ) from error
    result = _contracts(root).validate_contract("product-manifest", value)
    if not result["valid"]:
        detail = "\n  - ".join(result["errors"])
        raise ValueError(
            f"{source_path.relative_to(root)} is not a valid ProductManifest:\n  - {detail}"
        )
    slot_path = source_path.parent / EXTENSION_SLOT_FILE
    try:
        slots = json.loads(slot_path.read_text(encoding="utf-8"))
    except FileNotFoundError as error:
        raise ValueError(
            f"extension slot declarations are missing for profile {profile!r}: "
            f"{slot_path.relative_to(root)}"
        ) from error
    except json.JSONDecodeError as error:
        raise ValueError(f"{slot_path.relative_to(root)} is not valid JSON: {error.msg}") from error
    declared = value.get("extensions", {})
    actual_keys = set(slots).difference({"schema_version"})
    if actual_keys != set(declared):
        raise ValueError(
            f"{slot_path.relative_to(root)} extension keys do not match ProductManifest"
        )
    for key, reference in declared.items():
        if not isinstance(slots.get(key), dict) or slots[key].get("ref") != reference:
            raise ValueError(
                f"{slot_path.relative_to(root)} slot {key!r} does not match {reference!r}"
            )
    return value, source


def canonical_json(value: dict[str, Any]) -> str:
    return json.dumps(value, ensure_ascii=True, sort_keys=True, separators=(",", ":"))


def hashes(value: dict[str, Any], source: bytes) -> tuple[str, str]:
    canonical_hash = hashlib.sha256(canonical_json(value).encode("utf-8")).hexdigest()
    source_hash = hashlib.sha256(source).hexdigest()
    return canonical_hash, source_hash


def render_app(profile: str, value: dict[str, Any], source: bytes) -> str:
    canonical = canonical_json(value)
    canonical_hash, source_hash = hashes(value, source)
    return (
        "/* Generated by scripts/materialize-product-manifest.py; do not edit. */\n"
        "import type { ProductManifest } from '../lib/contracts-adapter';\n\n"
        f"export const PRODUCT_MANIFEST_PROFILE = {json.dumps(profile)} as const;\n"
        f"export const PRODUCT_MANIFEST_SOURCE_SHA256 = {json.dumps(source_hash)} as const;\n"
        f"export const PRODUCT_MANIFEST_SHA256 = {json.dumps(canonical_hash)} as const;\n"
        f"export const PRODUCT_MANIFEST_CANONICAL_JSON = {json.dumps(canonical)} as const;\n"
        "export const PRODUCT_MANIFEST = JSON.parse(\n"
        "  PRODUCT_MANIFEST_CANONICAL_JSON\n"
        ") as ProductManifest;\n"
    )


def render_agent(profile: str, value: dict[str, Any], source: bytes) -> str:
    canonical = canonical_json(value)
    canonical_hash, source_hash = hashes(value, source)
    return (
        '"""Generated by scripts/materialize-product-manifest.py; do not edit."""\n\n'
        "from __future__ import annotations\n\n"
        "import json\n\n"
        f"PRODUCT_MANIFEST_PROFILE = {json.dumps(profile)}\n"
        f"PRODUCT_MANIFEST_SOURCE_SHA256 = {json.dumps(source_hash)}\n"
        f"PRODUCT_MANIFEST_SHA256 = {json.dumps(canonical_hash)}\n"
        f"PRODUCT_MANIFEST_CANONICAL_JSON = {canonical!r}\n"
        "PRODUCT_MANIFEST = json.loads(PRODUCT_MANIFEST_CANONICAL_JSON)\n"
    )


def render_client(profile: str, value: dict[str, Any], source: bytes) -> str:
    canonical_hash, source_hash = hashes(value, source)
    safe = {
        "schemaVersion": value["schema_version"],
        "profile": profile,
        "manifestSha256": canonical_hash,
        "sourceSha256": source_hash,
        "product": value["product"],
        "presentation": value["presentation"],
        "extensions": {
            key: value["extensions"][key]
            for key in ("branding", "navigation", "loading", "settings", "export_chrome")
        },
        "exportChrome": {
            "formats": value["exports"]["formats"],
            "chromeRef": value["exports"].get("chrome_ref"),
            "documentTitle": value["exports"].get("document_title")
            or value["presentation"]["title"],
        },
    }
    return (
        "/* Generated by scripts/materialize-product-manifest.py; do not edit. */\n"
        "export const CLIENT_PRODUCT_MANIFEST = "
        f"{json.dumps(safe, ensure_ascii=True, sort_keys=True, separators=(',', ':'))} as const;\n"
    )


def outputs(root: Path, profile: str) -> dict[Path, str]:
    value, source = load_and_validate(root, profile)
    return {
        root / APP_OUTPUT: render_app(profile, value, source),
        root / CLIENT_OUTPUT: render_client(profile, value, source),
        root / AGENT_OUTPUT: render_agent(profile, value, source),
    }


def materialize(root: Path, profile: str, *, check: bool) -> None:
    stale: list[str] = []
    for path, expected in outputs(root, profile).items():
        if check:
            try:
                actual = path.read_text(encoding="utf-8")
            except FileNotFoundError:
                actual = ""
            if actual != expected:
                stale.append(str(path.relative_to(root)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")
    if stale:
        raise ValueError(
            "generated ProductManifest bindings drifted: "
            + ", ".join(stale)
            + f". Re-run with --profile {profile}."
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--profile",
        default=DEFAULT_PROFILE,
        help=(
            "explicit profiles/<name> selection "
            f"(default for this upstream repository: {DEFAULT_PROFILE})"
        ),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        materialize(ROOT, args.profile, check=args.check)
    except ValueError as error:
        print(f"ProductManifest materialization failed: {error}", file=sys.stderr)
        return 1
    verb = "matches" if args.check else "materialized"
    print(f"ProductManifest {args.profile!r} {verb} app, client, and agent bindings.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
